import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import vm from 'node:vm';
const read = file => readFileSync(new URL('../'+file, import.meta.url),'utf8');
const source = read('js/splash.js');
function harness({hidden=false,missingNumber=false,brokenFade=false,backNavigation=false,skipWelcome=false}={}) {
  let now=0, id=0;
  const pending=new Map(), events=new Map(), docEvents=new Map(), winEvents=new Map();
  const number={textContent:'3'};
  const splash={remove(){this.removed=true;},classList:{add(name){if(brokenFade)throw Error('animation failed');splash.leaving=name;}},addEventListener:(name,fn)=>events.set(name,fn),removeEventListener:name=>events.delete(name)};
  const document={documentElement:{classList:{contains:()=>skipWelcome}},hidden,getElementById:name=>name==='welcome-splash'?splash:missingNumber?null:number,addEventListener:(name,fn)=>docEvents.set(name,fn),removeEventListener:name=>docEvents.delete(name)};
  const window={performance:{getEntriesByType:()=>[{type:backNavigation?'back_forward':'navigate'}]},setTimeout(fn,delay){pending.set(++id,{fn,at:now+delay});return id;},clearTimeout:id=>pending.delete(id),addEventListener:(name,fn)=>winEvents.set(name,fn),removeEventListener:name=>winEvents.delete(name)};
  vm.runInNewContext(source,{document,window,Set});
  function tick(time){for(;;){const next=[...pending.entries()].filter(([,t])=>t.at<=time).sort((a,b)=>a[1].at-b[1].at)[0];if(!next)break;now=next[1].at;pending.delete(next[0]);try{next[1].fn();}catch{}}now=time;}
  return {splash,number,pending,events,docEvents,winEvents,document,tick};
}
assert.equal(harness({skipWelcome:true}).splash.removed,true);
assert.equal(harness({skipWelcome:true}).pending.size,0);
const normal=harness();
assert.equal(normal.number.textContent,'3');
normal.tick(999);assert.equal(normal.number.textContent,'3');
normal.tick(1000);assert.equal(normal.number.textContent,'2');
normal.tick(2000);assert.equal(normal.number.textContent,'1');
normal.tick(3000);assert.equal(normal.splash.leaving,'welcome-splash--leaving');
normal.tick(3500);assert.equal(normal.splash.removed,true);assert.equal(normal.pending.size,0);
assert.equal(normal.docEvents.size,0);assert.equal(normal.winEvents.size,0);assert.equal(normal.events.size,0);
const background=harness();background.document.hidden=true;background.docEvents.get('visibilitychange')();
assert.equal(background.splash.removed,true);assert.equal(background.pending.size,0);
const back=harness();back.winEvents.get('pagehide')();assert.equal(back.splash.removed,true);
assert.equal(harness({hidden:true}).pending.size,0);
assert.equal(harness({missingNumber:true}).splash.removed,true);
assert.equal(harness({backNavigation:true}).splash.removed,true);
const broken=harness({brokenFade:true});broken.tick(4500);assert.equal(broken.splash.removed,true);
const html=read('index.html'),css=read('css/splash.css'),sw=read('service-worker.js');
assert.match(html, /splash-emergency-exit .01s 4.8s forwards/);
assert.match(html, /<noscript><style>\.welcome-splash\{display:none\}/);
const markup=html.slice(html.indexOf('  <div class="welcome-splash"'),html.indexOf('  <a class="skip-link"'));
for(const word of ['冷轧焊接管理组','欢迎您','即将进入手册…'])assert.ok(markup.includes(word));
assert.match(markup, /<span style="--heat-delay:\.43s">欢<\/span><span style="--heat-delay:\.72s">迎<\/span><span style="--heat-delay:1\.01s">您<\/span>/);
assert.doesNotMatch(css, /@font-face|Splash Team Serif|Splash Welcome Brush|url\(/);
assert.match(css, /HarmonyOS Sans SC/);assert.match(css, /animation:splash-heat \.82s var\(--heat-delay\)/);
assert.match(css, /welcome-splash__title span,\.welcome-splash__sub/);
assert.equal((markup.match(/--heat-delay:/g)||[]).length,10);
assert.match(markup,/>精密焊接<\/p>/);assert.doesNotMatch(markup,/连续轧制/);
assert.match(markup,/<canvas class="welcome-splash__particles" id="welcome-sparks">/);
assert.doesNotMatch(markup,/welcome-splash__embers|welcome-splash__spark/);
assert.doesNotMatch(markup,/welcome-splash__background|welcome-splash__shade|<img/);
assert.doesNotMatch(html,/preload.*(?:splash-background|assets\/fonts)/);
assert.match(css,/splash-weld-travel 3s linear both/);assert.match(css,/splash-weld-fill 3s linear both/);
assert.doesNotMatch(css,/prefers-color-scheme/);assert.match(css,/--splash-bg:#02060e/);assert.match(css,/--splash-bg2:#0356c5/);
assert.match(css,/--splash-ink:#edf5ff/);assert.match(css,/--splash-hot:#55c9ff/);assert.match(css,/--splash-cool:#8caeff/);
assert.doesNotMatch(css,/\binfinite\b/);
assert.doesNotMatch(markup,/轻触屏幕|重新焊接/);
for(const delay of markup.matchAll(/--heat-delay:([\d.]+)s/g))assert.ok(Number(delay[1])+.82<2,'all letters cool before 2s');
assert.doesNotMatch(css, /https?:\/\//);
assert.doesNotMatch(markup, /<button|<a\s/);
assert.match(css,/7dvh/);assert.match(html,/height:100vh;height:100dvh/);
assert.match(css,/safe-area-inset-top/);assert.match(css,/safe-area-inset-bottom/);
assert.match(css,/prefers-reduced-motion:reduce/);
assert.doesNotMatch(source,/location|localStorage|sessionStorage|history\.|body\.style/);
for(const file of ['css/splash.css?v=10','js/splash.js?v=3','js/splash-sparks.js?v=1'])assert.ok(sw.includes('./'+file));
assert.doesNotMatch(sw,/splash-background\.webp|assets\/fonts\//);
assert.match(sw,/welding-guide-home-v37/);assert.match(sw,/name.startsWith\("welding-guide-home-"\)/);
const manifest=JSON.parse(read('manifest.json'));assert.equal(manifest.start_url,'./');assert.equal(manifest.scope,'./');
console.log('Splash: PASS (3→2→1, 3s fade, 3.5s removal, timers/listeners cleanup, hidden/pagehide, 4.5s failsafe, no JS fallback, isolated markup/styles, PWA paths)');
